apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-rentx
  annotations:
    github.com/project-slug: Leandro-Goncalves/api-rentx
spec:
  type: openapi
  lifecycle: unknown
  owner: guests
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
